import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
<<<<<<< HEAD
=======
import { AuthProvider } from "@/contexts/AuthContext";
import { ThemeProvider } from "next-themes";
>>>>>>> 67e2183 (Clean fixes and resolved issues for Nov 02)

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Personal Finance Visualizer",
<<<<<<< HEAD
  description: "Generated by create next app",
=======
  description: "Track your expenses, budgets, and insights with ease",
>>>>>>> 67e2183 (Clean fixes and resolved issues for Nov 02)
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
<<<<<<< HEAD
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
=======
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <AuthProvider>
            {children}
          </AuthProvider>
        </ThemeProvider>
>>>>>>> 67e2183 (Clean fixes and resolved issues for Nov 02)
      </body>
    </html>
  );
}
